# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labm8/data/test/ppar/protos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='labm8/data/test/ppar/protos.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n!labm8/data/test/ppar/protos.proto\"0\n\x08\x41\x64\x64XandY\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x0e\n\x06result\x18\x03 \x01(\x05\"3\n\x15UnexpectedOutputProto\x12\x1a\n\x12unexpected_message\x18\x01 \x01(\t')
)




_ADDXANDY = _descriptor.Descriptor(
  name='AddXandY',
  full_name='AddXandY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='AddXandY.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='AddXandY.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='AddXandY.result', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=85,
)


_UNEXPECTEDOUTPUTPROTO = _descriptor.Descriptor(
  name='UnexpectedOutputProto',
  full_name='UnexpectedOutputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unexpected_message', full_name='UnexpectedOutputProto.unexpected_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['AddXandY'] = _ADDXANDY
DESCRIPTOR.message_types_by_name['UnexpectedOutputProto'] = _UNEXPECTEDOUTPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddXandY = _reflection.GeneratedProtocolMessageType('AddXandY', (_message.Message,), dict(
  DESCRIPTOR = _ADDXANDY,
  __module__ = 'labm8.data.test.ppar.protos_pb2'
  # @@protoc_insertion_point(class_scope:AddXandY)
  ))
_sym_db.RegisterMessage(AddXandY)

UnexpectedOutputProto = _reflection.GeneratedProtocolMessageType('UnexpectedOutputProto', (_message.Message,), dict(
  DESCRIPTOR = _UNEXPECTEDOUTPUTPROTO,
  __module__ = 'labm8.data.test.ppar.protos_pb2'
  # @@protoc_insertion_point(class_scope:UnexpectedOutputProto)
  ))
_sym_db.RegisterMessage(UnexpectedOutputProto)


# @@protoc_insertion_point(module_scope)
