# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clgen/proto/sampler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clgen/proto/sampler.proto',
  package='clgen',
  syntax='proto2',
  serialized_options=_b('\n\022deeplearning.clgen'),
  serialized_pb=_b('\n\x19\x63lgen/proto/sampler.proto\x12\x05\x63lgen\"\x8e\x01\n\x07Sampler\x12\x12\n\nstart_text\x18\x01 \x01(\t\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x1a\n\x12temperature_micros\x18\x03 \x01(\x05\x12?\n\x14termination_criteria\x18\x04 \x03(\x0b\x32!.clgen.SampleTerminationCriterion\"\x82\x01\n\x1aSampleTerminationCriterion\x12\'\n\x06maxlen\x18\x01 \x01(\x0b\x32\x15.clgen.MaxTokenLengthH\x00\x12.\n\x06symtok\x18\x02 \x01(\x0b\x32\x1c.clgen.SymmetricalTokenDepthH\x00\x42\x0b\n\tcriterion\"2\n\x0eMaxTokenLength\x12 \n\x18maximum_tokens_in_sample\x18\x01 \x01(\x05\"S\n\x15SymmetricalTokenDepth\x12\x1c\n\x14\x64\x65pth_increase_token\x18\x01 \x01(\t\x12\x1c\n\x14\x64\x65pth_decrease_token\x18\x02 \x01(\tB\x14\n\x12\x64\x65\x65plearning.clgen')
)




_SAMPLER = _descriptor.Descriptor(
  name='Sampler',
  full_name='clgen.Sampler',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_text', full_name='clgen.Sampler.start_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='clgen.Sampler.batch_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature_micros', full_name='clgen.Sampler.temperature_micros', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='termination_criteria', full_name='clgen.Sampler.termination_criteria', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=179,
)


_SAMPLETERMINATIONCRITERION = _descriptor.Descriptor(
  name='SampleTerminationCriterion',
  full_name='clgen.SampleTerminationCriterion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='maxlen', full_name='clgen.SampleTerminationCriterion.maxlen', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symtok', full_name='clgen.SampleTerminationCriterion.symtok', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='criterion', full_name='clgen.SampleTerminationCriterion.criterion',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=182,
  serialized_end=312,
)


_MAXTOKENLENGTH = _descriptor.Descriptor(
  name='MaxTokenLength',
  full_name='clgen.MaxTokenLength',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='maximum_tokens_in_sample', full_name='clgen.MaxTokenLength.maximum_tokens_in_sample', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=364,
)


_SYMMETRICALTOKENDEPTH = _descriptor.Descriptor(
  name='SymmetricalTokenDepth',
  full_name='clgen.SymmetricalTokenDepth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='depth_increase_token', full_name='clgen.SymmetricalTokenDepth.depth_increase_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_decrease_token', full_name='clgen.SymmetricalTokenDepth.depth_decrease_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=449,
)

_SAMPLER.fields_by_name['termination_criteria'].message_type = _SAMPLETERMINATIONCRITERION
_SAMPLETERMINATIONCRITERION.fields_by_name['maxlen'].message_type = _MAXTOKENLENGTH
_SAMPLETERMINATIONCRITERION.fields_by_name['symtok'].message_type = _SYMMETRICALTOKENDEPTH
_SAMPLETERMINATIONCRITERION.oneofs_by_name['criterion'].fields.append(
  _SAMPLETERMINATIONCRITERION.fields_by_name['maxlen'])
_SAMPLETERMINATIONCRITERION.fields_by_name['maxlen'].containing_oneof = _SAMPLETERMINATIONCRITERION.oneofs_by_name['criterion']
_SAMPLETERMINATIONCRITERION.oneofs_by_name['criterion'].fields.append(
  _SAMPLETERMINATIONCRITERION.fields_by_name['symtok'])
_SAMPLETERMINATIONCRITERION.fields_by_name['symtok'].containing_oneof = _SAMPLETERMINATIONCRITERION.oneofs_by_name['criterion']
DESCRIPTOR.message_types_by_name['Sampler'] = _SAMPLER
DESCRIPTOR.message_types_by_name['SampleTerminationCriterion'] = _SAMPLETERMINATIONCRITERION
DESCRIPTOR.message_types_by_name['MaxTokenLength'] = _MAXTOKENLENGTH
DESCRIPTOR.message_types_by_name['SymmetricalTokenDepth'] = _SYMMETRICALTOKENDEPTH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sampler = _reflection.GeneratedProtocolMessageType('Sampler', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLER,
  __module__ = 'clgen.proto.sampler_pb2'
  # @@protoc_insertion_point(class_scope:clgen.Sampler)
  ))
_sym_db.RegisterMessage(Sampler)

SampleTerminationCriterion = _reflection.GeneratedProtocolMessageType('SampleTerminationCriterion', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLETERMINATIONCRITERION,
  __module__ = 'clgen.proto.sampler_pb2'
  # @@protoc_insertion_point(class_scope:clgen.SampleTerminationCriterion)
  ))
_sym_db.RegisterMessage(SampleTerminationCriterion)

MaxTokenLength = _reflection.GeneratedProtocolMessageType('MaxTokenLength', (_message.Message,), dict(
  DESCRIPTOR = _MAXTOKENLENGTH,
  __module__ = 'clgen.proto.sampler_pb2'
  # @@protoc_insertion_point(class_scope:clgen.MaxTokenLength)
  ))
_sym_db.RegisterMessage(MaxTokenLength)

SymmetricalTokenDepth = _reflection.GeneratedProtocolMessageType('SymmetricalTokenDepth', (_message.Message,), dict(
  DESCRIPTOR = _SYMMETRICALTOKENDEPTH,
  __module__ = 'clgen.proto.sampler_pb2'
  # @@protoc_insertion_point(class_scope:clgen.SymmetricalTokenDepth)
  ))
_sym_db.RegisterMessage(SymmetricalTokenDepth)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
