# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clgen/proto/telemetry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clgen/proto/telemetry.proto',
  package='clgen',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x63lgen/proto/telemetry.proto\x12\x05\x63lgen\"r\n\x13ModelEpochTelemetry\x12\x1e\n\x16timestamp_utc_epoch_ms\x18\x01 \x01(\x03\x12\x11\n\tepoch_num\x18\x02 \x01(\x05\x12\x1a\n\x12\x65poch_wall_time_ms\x18\x03 \x01(\x03\x12\x0c\n\x04loss\x18\x04 \x01(\x01')
)




_MODELEPOCHTELEMETRY = _descriptor.Descriptor(
  name='ModelEpochTelemetry',
  full_name='clgen.ModelEpochTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_utc_epoch_ms', full_name='clgen.ModelEpochTelemetry.timestamp_utc_epoch_ms', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_num', full_name='clgen.ModelEpochTelemetry.epoch_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_wall_time_ms', full_name='clgen.ModelEpochTelemetry.epoch_wall_time_ms', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loss', full_name='clgen.ModelEpochTelemetry.loss', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['ModelEpochTelemetry'] = _MODELEPOCHTELEMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelEpochTelemetry = _reflection.GeneratedProtocolMessageType('ModelEpochTelemetry', (_message.Message,), dict(
  DESCRIPTOR = _MODELEPOCHTELEMETRY,
  __module__ = 'clgen.proto.telemetry_pb2'
  # @@protoc_insertion_point(class_scope:clgen.ModelEpochTelemetry)
  ))
_sym_db.RegisterMessage(ModelEpochTelemetry)


# @@protoc_insertion_point(module_scope)
