# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tools/code_style/templates/proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tools/code_style/templates/proto.proto',
  package='tools.code_style.templates',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n&tools/code_style/templates/proto.proto\x12\x1atools.code_style.templates\"\x15\n\x04Todo\x12\r\n\x05\x66ield\x18\x01 \x01(\t')
)




_TODO = _descriptor.Descriptor(
  name='Todo',
  full_name='tools.code_style.templates.Todo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='tools.code_style.templates.Todo.field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['Todo'] = _TODO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Todo = _reflection.GeneratedProtocolMessageType('Todo', (_message.Message,), dict(
  DESCRIPTOR = _TODO,
  __module__ = 'tools.code_style.templates.proto_pb2'
  # @@protoc_insertion_point(class_scope:tools.code_style.templates.Todo)
  ))
_sym_db.RegisterMessage(Todo)


# @@protoc_insertion_point(module_scope)
