# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labm8/proto/test_protos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='labm8/proto/test_protos.proto',
  package='labm8',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1dlabm8/proto/test_protos.proto\x12\x05labm8\"d\n\x0bTestMessage\x12\x0e\n\x06string\x18\x01 \x02(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\x12\x12\n\x08option_a\x18\x03 \x01(\x05H\x00\x12\x12\n\x08option_b\x18\x04 \x01(\x05H\x00\x42\r\n\x0bunion_field\"$\n\x12\x41notherTestMessage\x12\x0e\n\x06number\x18\x01 \x01(\x05')
)




_TESTMESSAGE = _descriptor.Descriptor(
  name='TestMessage',
  full_name='labm8.TestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string', full_name='labm8.TestMessage.string', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='labm8.TestMessage.number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='option_a', full_name='labm8.TestMessage.option_a', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='option_b', full_name='labm8.TestMessage.option_b', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='union_field', full_name='labm8.TestMessage.union_field',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=40,
  serialized_end=140,
)


_ANOTHERTESTMESSAGE = _descriptor.Descriptor(
  name='AnotherTestMessage',
  full_name='labm8.AnotherTestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='labm8.AnotherTestMessage.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=178,
)

_TESTMESSAGE.oneofs_by_name['union_field'].fields.append(
  _TESTMESSAGE.fields_by_name['option_a'])
_TESTMESSAGE.fields_by_name['option_a'].containing_oneof = _TESTMESSAGE.oneofs_by_name['union_field']
_TESTMESSAGE.oneofs_by_name['union_field'].fields.append(
  _TESTMESSAGE.fields_by_name['option_b'])
_TESTMESSAGE.fields_by_name['option_b'].containing_oneof = _TESTMESSAGE.oneofs_by_name['union_field']
DESCRIPTOR.message_types_by_name['TestMessage'] = _TESTMESSAGE
DESCRIPTOR.message_types_by_name['AnotherTestMessage'] = _ANOTHERTESTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestMessage = _reflection.GeneratedProtocolMessageType('TestMessage', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE,
  __module__ = 'labm8.proto.test_protos_pb2'
  # @@protoc_insertion_point(class_scope:labm8.TestMessage)
  ))
_sym_db.RegisterMessage(TestMessage)

AnotherTestMessage = _reflection.GeneratedProtocolMessageType('AnotherTestMessage', (_message.Message,), dict(
  DESCRIPTOR = _ANOTHERTESTMESSAGE,
  __module__ = 'labm8.proto.test_protos_pb2'
  # @@protoc_insertion_point(class_scope:labm8.AnotherTestMessage)
  ))
_sym_db.RegisterMessage(AnotherTestMessage)


# @@protoc_insertion_point(module_scope)
